/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_senha;

import Tela.Menu;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hfranca
 */
public class Login_Senha extends javax.swing.JFrame {

    /**
     * Creates new form Login_Senha
     * @throws java.lang.ClassNotFoundException
     */
    public Login_Senha() throws ClassNotFoundException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Acessar = new javax.swing.JButton();
        Fechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CampoLogin = new javax.swing.JTextField();
        CampoSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login");
        getContentPane().setLayout(null);

        Acessar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Acessar.setForeground(new java.awt.Color(0, 0, 102));
        Acessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bold6.png"))); // NOI18N
        Acessar.setText("  Acessar");
        Acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcessarActionPerformed(evt);
            }
        });
        getContentPane().add(Acessar);
        Acessar.setBounds(110, 520, 131, 46);

        Fechar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fechar.setForeground(new java.awt.Color(204, 0, 0));
        Fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/close18.png"))); // NOI18N
        Fechar.setText("  Fechar");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });
        getContentPane().add(Fechar);
        Fechar.setBounds(290, 520, 137, 46);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tela de Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 70, 191, 41);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuário/CRM: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 340, 110, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 420, 80, 37);

        CampoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoLoginActionPerformed(evt);
            }
        });
        getContentPane().add(CampoLogin);
        CampoLogin.setBounds(150, 340, 270, 40);

        CampoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(CampoSenha);
        CampoSenha.setBounds(149, 420, 270, 37);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LogoG.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 160, 460, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Background.jpg"))); // NOI18N
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -5, 580, 670);

        setSize(new java.awt.Dimension(595, 706));
    }// </editor-fold>//GEN-END:initComponents

    private void AcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcessarActionPerformed

        buscarUsuarioXML();
       /* String Usuario = "Teste";

        if (Login.getText().equalsIgnoreCase(Usuario)&& (Senha.getText().equals("123"))){

            JOptionPane.showMessageDialog(null, "Usuário: "+Usuario+"\nAcesso autorizado.");
            
            try {
                new Menu().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login_Senha.class.getName()).log(Level.SEVERE, null, ex);
            }
           
              
           
            this.dispose();//FECHA A TELA ATUAL.

        }

        else {
            JOptionPane.showMessageDialog(null, "Acesso Negado, usuário ou senha está incorreto\nPara testes, Utilizar o usuário teste e senha 123.");
        }*/

    }//GEN-LAST:event_AcessarActionPerformed

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        System.exit(0);

    }//GEN-LAST:event_FecharActionPerformed

    private void CampoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoLoginActionPerformed

    private void CampoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login_Senha().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Login_Senha.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acessar;
    private javax.swing.JTextField CampoLogin;
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JButton Fechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
//=====================================================================================
  

public void buscarUsuarioXML(){
    
    
     String crm=CampoLogin.getText().trim();
    
                   
             String AuxCRM="", AuxSenha="", AuxNome="";
             String nome;
             String senha;
             String sexo;
             String email;
             String data;
             String tipo;
                  
             String mostra="";
	     String nomeArq="Cadastro/usuario/"+crm+".xml"; //Nome do arquivo, pode ser absoluto, ou pastas /dir/teste.txt
	     String linha="";
	     
		File arq = new File(nomeArq);
		
		//Arquivo existe
		if (arq.exists()){
		//	mostra="Arquivo - '"+nomeArq+"', aberto com sucesso!\n";
		//	mostra+="Tamanho do arquivo "+Long.toString(arq.length())+"\n";
		
                    //tentando ler arquivo
			try{
				
				FileReader reader = new FileReader(nomeArq); //abrindo arquivo para leitura
				BufferedReader leitor = new BufferedReader(reader); //leitor do arquivo
				
				leitor.readLine(); //<xml
				leitor.readLine(); //<cadastro
                                leitor.readLine(); //<Paciente
				while(true){
                                
					crm=leitor.readLine();
                                        crm=crm.substring(crm.indexOf(">")+1,crm.indexOf("/")-1); //pegando entre as tags
                                        AuxCRM=crm;
                                        
					nome=leitor.readLine();
                                        nome=nome.substring(nome.indexOf(">")+1,nome.indexOf("/")-1); //pegando entre as tags
                                        AuxNome=nome;
                             
                                       
                                        senha=leitor.readLine();
                                        senha=senha.substring(senha.indexOf(">")+1,senha.indexOf("/")-1); //pegando entre as tags
                                        AuxSenha=senha;
                                        			                
                                        sexo=leitor.readLine();
                                        sexo=sexo.substring(sexo.indexOf(">")+1,sexo.indexOf("/")-1); //pegando entre as tags
                                      
                                                                                                                                                                                                 
                                        tipo=leitor.readLine();
                                        tipo=tipo.substring(tipo.indexOf(">")+1,tipo.indexOf("/")-1);
                                     
                                        
                                      
                                        
                                        email=leitor.readLine();
                                        email=email.substring(email.indexOf(">")+1,email.indexOf("/")-1);
                                      
                                        
                                        data=leitor.readLine(); 
                                        data=data.substring(data.indexOf(">")+1,data.indexOf("/")-1);
                                        
                                        
                                         mostra+="Usuário: "+ nome+"\n\n";
                                        /* mostra+="Registro: "+registro
                                                +"\nNome: "+nome
                                                +"\nCPF: "+cpf
                                                +"\nData de Nascimento: "+dataNasc
                                                +"\nSexo: "+sexo
                                                +"\nEndereço: "+endereco
                                                +"\nTelefone: "+telefone
                                                +"\nE-mail: "+email
                                                +"\nData: "+data+"\n";   */                                                       
			             
					
                                     if(nome==null){break;}
				
                                }
                                        
                                                 
                                        
			}
			catch(Exception erro) {
			//JOptionPane.showMessageDialog(null,mostra,"Arquivo (catch)",1);
		}}
		//Se nao existir
		else
			JOptionPane.showMessageDialog(null,"Falha no login, Usuário nao existe!","Erro",0);
	

	
                
                
              

        if (CampoLogin.getText().trim().equalsIgnoreCase(AuxCRM)&& (CampoSenha.getText().trim().equalsIgnoreCase(AuxSenha))){

            JOptionPane.showMessageDialog(null, "Acesso autorizado.\nUsuário(a), "+AuxNome);
            
            try {
                new Menu().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login_Senha.class.getName()).log(Level.SEVERE, null, ex);
            }
           
              
           
            this.dispose();//FECHA A TELA ATUAL.

        }

        else {
            JOptionPane.showMessageDialog(null, "Acesso Negado, usuário ou senha está incorreto.\nPara testar, Utilizar o usuário teste e senha 123,\n ou usuário adm, senha adm.");
        }
                
                
         }       
                
                
}

//=====================================================================================



