/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuarios;

import Paciente.*;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Formatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Helio Franca
 */
public class Buscar_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Buscar_P
     */
    public Buscar_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2_Sexo = new javax.swing.ButtonGroup();
        buttonGroup1_Busca = new javax.swing.ButtonGroup();
        Pesquisar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        Fechar = new javax.swing.JButton();
        BuscarNome = new javax.swing.JRadioButton();
        BuscaRegistro = new javax.swing.JRadioButton();
        CampoBuscarNome = new javax.swing.JTextField();
        CampoBuscarCRM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTCRM = new javax.swing.JTextField();
        jTnome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTSenha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTData = new javax.swing.JTextField();
        jTEmail = new javax.swing.JTextField();
        Gravar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtTipo = new javax.swing.JTextField();
        jTSexo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar usuário");
        getContentPane().setLayout(null);

        Pesquisar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifier13.png"))); // NOI18N
        Pesquisar.setText("  Pesquisar");
        Pesquisar.setToolTipText("");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(Pesquisar);
        Pesquisar.setBounds(550, 80, 130, 40);

        Excluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Excluir.setForeground(new java.awt.Color(255, 0, 0));
        Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/close18.png"))); // NOI18N
        Excluir.setText("  Limpar");
        Excluir.setToolTipText("");
        Excluir.setEnabled(false);
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(Excluir);
        Excluir.setBounds(220, 530, 115, 40);

        Atualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/refresh18.png"))); // NOI18N
        Atualizar.setText("Atualizar");
        Atualizar.setToolTipText("");
        Atualizar.setEnabled(false);
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Atualizar);
        Atualizar.setBounds(50, 530, 130, 40);

        Fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/left176.png"))); // NOI18N
        Fechar.setToolTipText("");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });
        getContentPane().add(Fechar);
        Fechar.setBounds(860, 530, 49, 39);

        buttonGroup1_Busca.add(BuscarNome);
        BuscarNome.setText("Buscar pelo nome");
        BuscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarNomeActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarNome);
        BuscarNome.setBounds(50, 90, 130, 30);

        buttonGroup1_Busca.add(BuscaRegistro);
        BuscaRegistro.setText("Buscar pelo CRM");
        BuscaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(BuscaRegistro);
        BuscaRegistro.setBounds(50, 130, 140, 30);

        CampoBuscarNome.setEditable(false);
        CampoBuscarNome.setEnabled(false);
        CampoBuscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoBuscarNomeActionPerformed(evt);
            }
        });
        CampoBuscarNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoBuscarNomeKeyReleased(evt);
            }
        });
        getContentPane().add(CampoBuscarNome);
        CampoBuscarNome.setBounds(190, 90, 190, 27);

        CampoBuscarCRM.setEnabled(false);
        CampoBuscarCRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoBuscarCRMActionPerformed(evt);
            }
        });
        CampoBuscarCRM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoBuscarCRMKeyTyped(evt);
            }
        });
        getContentPane().add(CampoBuscarCRM);
        CampoBuscarCRM.setBounds(190, 130, 150, 27);

        jLabel1.setText("CRM:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(620, 270, 50, 20);

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 230, 40, 20);

        jTCRM.setEditable(false);
        jTCRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCRMActionPerformed(evt);
            }
        });
        getContentPane().add(jTCRM);
        jTCRM.setBounds(670, 270, 100, 30);

        jTnome.setEditable(false);
        jTnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTnome);
        jTnome.setBounds(120, 220, 410, 30);

        jLabel7.setText("Senha: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 280, 70, 20);

        jTSenha.setEditable(false);
        getContentPane().add(jTSenha);
        jTSenha.setBounds(120, 270, 170, 30);

        jLabel8.setText("E-Mail:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 330, 40, 20);

        jLabel6.setText("Tipo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 280, 40, 20);

        jTData.setEditable(false);
        jTData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDataActionPerformed(evt);
            }
        });
        getContentPane().add(jTData);
        jTData.setBounds(670, 210, 240, 30);

        jTEmail.setEditable(false);
        jTEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTEmail);
        jTEmail.setBounds(120, 320, 410, 30);

        Gravar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Gravar.setForeground(new java.awt.Color(0, 0, 102));
        Gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bold6.png"))); // NOI18N
        Gravar.setText("  Gravar");
        Gravar.setToolTipText("");
        Gravar.setEnabled(false);
        Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GravarActionPerformed(evt);
            }
        });
        getContentPane().add(Gravar);
        Gravar.setBounds(50, 400, 130, 40);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(50, 490, 860, 10);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(50, 200, 860, 2);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("Buscar  Usuário:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 10, 300, 50);

        jLabel3.setText("Desabilitado");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 90, 70, 20);

        jLabel4.setText("Data:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(620, 210, 60, 30);

        jtTipo.setEditable(false);
        jtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jtTipo);
        jtTipo.setBounds(410, 270, 120, 30);

        jTSexo.setEditable(false);
        jTSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSexoActionPerformed(evt);
            }
        });
        getContentPane().add(jTSexo);
        jTSexo.setBounds(670, 320, 100, 30);

        jLabel11.setText("Sexo:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(620, 330, 30, 20);

        setSize(new java.awt.Dimension(1065, 654));
    }// </editor-fold>//GEN-END:initComponents

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        buscarXML();
        Atualizar.setEnabled(true);
        Excluir.setEnabled(true);
        
    }//GEN-LAST:event_PesquisarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
jTextApagar();
    }//GEN-LAST:event_ExcluirActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed

        atualizar();
        Gravar.setEnabled(true);
    }//GEN-LAST:event_AtualizarActionPerformed

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        dispose();
    }//GEN-LAST:event_FecharActionPerformed

    private void BuscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarNomeActionPerformed

        if(BuscarNome.isSelected()){
            CampoBuscarNome.setEnabled(true);
            CampoBuscarCRM.setEnabled(false);

}
        
    }//GEN-LAST:event_BuscarNomeActionPerformed

    private void BuscaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaRegistroActionPerformed

        

if(BuscaRegistro.isSelected()){
CampoBuscarCRM.setEnabled(true);
  CampoBuscarNome.setEnabled(false);
}


        
        
    }//GEN-LAST:event_BuscaRegistroActionPerformed

    private void CampoBuscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoBuscarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoBuscarNomeActionPerformed

    private void CampoBuscarNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoBuscarNomeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoBuscarNomeKeyReleased

    private void CampoBuscarCRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoBuscarCRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoBuscarCRMActionPerformed

    private void CampoBuscarCRMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoBuscarCRMKeyTyped

    }//GEN-LAST:event_CampoBuscarCRMKeyTyped

    private void jTCRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCRMActionPerformed

    private void jTnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnomeActionPerformed

    private void jTEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEmailActionPerformed

    private void GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GravarActionPerformed
salvarXML();
Editablefalse();
    }//GEN-LAST:event_GravarActionPerformed

    private void jTDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDataActionPerformed

    private void jtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTipoActionPerformed

    private void jTSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSexoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JRadioButton BuscaRegistro;
    private javax.swing.JRadioButton BuscarNome;
    private javax.swing.JTextField CampoBuscarCRM;
    private javax.swing.JTextField CampoBuscarNome;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Fechar;
    private javax.swing.JButton Gravar;
    private javax.swing.JButton Pesquisar;
    private javax.swing.ButtonGroup buttonGroup1_Busca;
    private javax.swing.ButtonGroup buttonGroup2_Sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTCRM;
    private javax.swing.JTextField jTData;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTSenha;
    private javax.swing.JTextField jTSexo;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jtTipo;
    // End of variables declaration//GEN-END:variables



//=====================================================================================
  

public void atualizar(){
    
    jTCRM.setEditable(true);
    jTnome.setEditable(true);
    jTEmail.setEditable(true);
    //jTData.setEditable(true);
    jTSenha.setEditable(true);
    jtTipo.setEditable(true);
    jTSexo.setEditable(true);
    




}

//=====================================================================================
  

public void buscarXML(){
    
    String crm="";
    
     
   if(BuscarNome.isSelected()){
      crm = CampoBuscarNome.getText().trim();
   }
   if(BuscaRegistro.isSelected()){
      crm = CampoBuscarCRM.getText().trim();
   }
               
             String CRM;
             String nome;
             String senha;
             String sexo;
             String email;
             String data;
             String tipo;
                  
             String mostra="";
	     String nomeArq="Cadastro/usuario/"+crm+".xml"; //Nome do arquivo, pode ser absoluto, ou pastas /dir/teste.txt
	     String linha="";
	     
		File arq = new File(nomeArq);
		
		//Arquivo existe
		if (arq.exists()){
		//	mostra="Arquivo - '"+nomeArq+"', aberto com sucesso!\n";
		//	mostra+="Tamanho do arquivo "+Long.toString(arq.length())+"\n";
		
                    //tentando ler arquivo
			try{
				
				FileReader reader = new FileReader(nomeArq); //abrindo arquivo para leitura
				BufferedReader leitor = new BufferedReader(reader); //leitor do arquivo
				
				leitor.readLine(); //<xml
				leitor.readLine(); //<cadastro
                                leitor.readLine(); //<Paciente
				while(true){
                                
					crm=leitor.readLine();
                                        crm=crm.substring(crm.indexOf(">")+1,crm.indexOf("/")-1); //pegando entre as tags
                                        jTCRM.setText(crm);
                                        
					nome=leitor.readLine();
                                        nome=nome.substring(nome.indexOf(">")+1,nome.indexOf("/")-1); //pegando entre as tags
                                        jTnome.setText(nome);
                                       
                                        senha=leitor.readLine();
                                        senha=senha.substring(senha.indexOf(">")+1,senha.indexOf("/")-1); //pegando entre as tags
                                        jTSenha.setText(senha);
                                        			                
                                        sexo=leitor.readLine();
                                        sexo=sexo.substring(sexo.indexOf(">")+1,sexo.indexOf("/")-1); //pegando entre as tags
                                        jTSexo.setText(sexo);
                                                                                                                                                                                                 
                                        tipo=leitor.readLine();
                                        tipo=tipo.substring(tipo.indexOf(">")+1,tipo.indexOf("/")-1);
                                        jTData.setText(tipo);
                                        
                                      
                                        
                                        email=leitor.readLine();
                                        email=email.substring(email.indexOf(">")+1,email.indexOf("/")-1);
                                        jTEmail.setText(email);
                                        
                                        data=leitor.readLine(); 
                                        data=data.substring(data.indexOf(">")+1,data.indexOf("/")-1);
                                        jtTipo.setText(data);
                                        
                                         mostra+="Usuário: "+ nome+"\n\n";
                                        /* mostra+="Registro: "+registro
                                                +"\nNome: "+nome
                                                +"\nCPF: "+cpf
                                                +"\nData de Nascimento: "+dataNasc
                                                +"\nSexo: "+sexo
                                                +"\nEndereço: "+endereco
                                                +"\nTelefone: "+telefone
                                                +"\nE-mail: "+email
                                                +"\nData: "+data+"\n";   */                                                       
			             
					
                                     if(nome==null){break;}
				
                                }
                                        
                                                 
                                        
			}
			catch(Exception erro) {
			//JOptionPane.showMessageDialog(null,mostra,"Arquivo (catch)",1);
		}}
		//Se nao existir
		else
			JOptionPane.showMessageDialog(null,"Arquivo nao existe!","Erro",0);
	
}

//=====================================================================================
  
public void salvarXML(){//Salva as informações em XML.
                               
             String crm= jTCRM.getText().trim();
             String nome= jTnome.getText().trim();
              String senha= jTSenha.getText().trim();
                  
             String tipo=jTData.getText().trim();
             String email=jTEmail.getText().trim();
             String sexo=jTSexo.getText().trim();
             String data=jtTipo.getText().trim(); 
                
                   
		//String nomeArq="Cadastro/"+registro+"_"+nome+".xml";
                String nomeArq="Cadastro/usuario/"+crm+".xml";
             
		String texto;
		//tentando criar arquivo
		try
		{
                try (Formatter saida = new Formatter(nomeArq)) {
                    texto="<?xml version='1.0' encoding='ISO-8859-1' ?>\n"+
                            "<cadastros>\n";
                                       
                   texto+=" <Usuario>\n";
                    texto+=" <Registro>"+crm+"</Registro>\n";
                    texto+=" <Nome>"+nome+"</Nome>\n";
                    texto+=" <CPF>"+senha+"</CPF>\n";
                    texto+=" <Sexo>"+sexo+"</Sexo>\n";
                    texto+=" <E_mail>"+email+"</E_mail>\n";
                    texto+=" <Data>"+data+"</Data>\n";
                    texto+=" <Data>"+tipo+"</Data>\n";
                    texto+=" </Paciente>\n";
                    texto+="</Usuario>";
                    saida.format(texto);
                    
                }
			JOptionPane.showMessageDialog(null,"Arquivo '"+nomeArq+"' criado!","Arquivo",1);
		}
		//mostrando erro em caso se nao for possivel gerar arquivo
		catch(FileNotFoundException | HeadlessException erro){
			JOptionPane.showMessageDialog(null,"Arquivo nao pode ser gerado!","Erro",0);
                
        }
}

//=====================================================================================
    
public void jTextApagar(){//Apaga os textos dos jTexts

//Zera os campos JText.    
//jT_Registro.setText("");
             jTCRM.setText("");
             jTnome.setText("");
             jTSenha.setText("");
                  
             jTData.setText("");
             jTEmail.setText("");
             jTSexo.setText("");
             jtTipo.setText("");

}


//=====================================================================================
    
public void Editablefalse(){//Apaga os textos dos jTexts

jTCRM.setEditable(false);
    jTnome.setEditable(false);
    jTEmail.setEditable(false);
    //jTData.setEditable(true);
    jTSenha.setEditable(false);
    jtTipo.setEditable(false);
    jTSexo.setEditable(false);
}
}