// referência-https://pt.wikipedia.org/wiki/Anamnese_%28sa%C3%BAde%29


package Atendimento;



import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

//...

/**
 *
 * @author Helio Franca
 */
public class Preencher_anamnese extends javax.swing.JFrame {
    

 //Aqui eu chamo as variaveis para conexao, envio e recebimento

 
 
    public Preencher_anamnese()  {
        initComponents();
        
     
     Calendar data = Calendar.getInstance(); 
     CampoDataAtual.setText(data.getTime().toString());
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1_Bebidas = new javax.swing.ButtonGroup();
        buttonGroup2_Drogas = new javax.swing.ButtonGroup();
        buttonGroup1_Fuma = new javax.swing.ButtonGroup();
        buttonGroup1_Deficiencia = new javax.swing.ButtonGroup();
        buttonGroup1_Doença = new javax.swing.ButtonGroup();
        CampoBuscarNome = new javax.swing.JTextField();
        jLabel_Nome = new javax.swing.JLabel();
        CampoBuscarRegistro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CampoDataNasc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        Gravar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CampoAltura = new javax.swing.JTextField();
        CampoPeso = new javax.swing.JTextField();
        Fsim = new javax.swing.JRadioButton();
        Fnao = new javax.swing.JRadioButton();
        UDsim = new javax.swing.JRadioButton();
        UDnao = new javax.swing.JRadioButton();
        BASim = new javax.swing.JRadioButton();
        BANao = new javax.swing.JRadioButton();
        DEsim = new javax.swing.JRadioButton();
        DEnao = new javax.swing.JRadioButton();
        Dosim = new javax.swing.JRadioButton();
        DOnao = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CampoObservacao = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CampoConsultaN = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        CampoNomeMedico = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        CampoDataAtual = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CampoTratamento = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        CampoRemedio = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        Fechar = new javax.swing.JButton();
        CampoAnamneseN = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anamneses");
        getContentPane().setLayout(null);

        CampoBuscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoBuscarNomeActionPerformed(evt);
            }
        });
        CampoBuscarNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoBuscarNomeKeyReleased(evt);
            }
        });
        getContentPane().add(CampoBuscarNome);
        CampoBuscarNome.setBounds(140, 100, 330, 27);

        jLabel_Nome.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel_Nome.setText("Nome:");
        getContentPane().add(jLabel_Nome);
        jLabel_Nome.setBounds(60, 100, 60, 25);

        CampoBuscarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoBuscarRegistroActionPerformed(evt);
            }
        });
        CampoBuscarRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoBuscarRegistroKeyTyped(evt);
            }
        });
        getContentPane().add(CampoBuscarRegistro);
        CampoBuscarRegistro.setBounds(610, 100, 60, 27);

        jLabel3.setText("Data de Nascimento:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 150, 120, 14);
        getContentPane().add(CampoDataNasc);
        CampoDataNasc.setBounds(580, 140, 90, 30);

        jLabel7.setText("CPF: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 150, 40, 14);

        jTextField7.setEnabled(false);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(140, 140, 260, 30);

        jLabel8.setText("E-Mail:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(430, 230, 50, 14);

        jLabel5.setText("Telefone:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 230, 60, 14);

        jLabel6.setText("Endereço:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 190, 60, 14);

        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(140, 220, 230, 30);

        jTextField5.setEnabled(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(140, 180, 530, 30);

        jTextField6.setEnabled(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(480, 220, 190, 30);

        Gravar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Gravar.setForeground(new java.awt.Color(0, 0, 102));
        Gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bold6.png"))); // NOI18N
        Gravar.setText(" Gravar");
        Gravar.setToolTipText("");
        Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GravarActionPerformed(evt);
            }
        });
        getContentPane().add(Gravar);
        Gravar.setBounds(60, 680, 170, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Bebidas alcoólicas:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 470, 140, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("KG");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 420, 60, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Fuma:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 470, 50, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Deficiencia:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(330, 510, 70, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Doenças:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(550, 470, 70, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Uso de drogas:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(60, 510, 120, 20);
        getContentPane().add(CampoAltura);
        CampoAltura.setBounds(340, 410, 70, 30);

        CampoPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoPeso);
        CampoPeso.setBounds(130, 410, 70, 30);

        buttonGroup1_Fuma.add(Fsim);
        Fsim.setText("Sim");
        getContentPane().add(Fsim);
        Fsim.setBounds(410, 470, 50, 23);

        buttonGroup1_Fuma.add(Fnao);
        Fnao.setText("Não");
        getContentPane().add(Fnao);
        Fnao.setBounds(470, 470, 50, 23);

        buttonGroup2_Drogas.add(UDsim);
        UDsim.setText("Sim");
        getContentPane().add(UDsim);
        UDsim.setBounds(180, 510, 50, 23);

        buttonGroup2_Drogas.add(UDnao);
        UDnao.setText("Não");
        getContentPane().add(UDnao);
        UDnao.setBounds(240, 510, 60, 23);

        buttonGroup1_Bebidas.add(BASim);
        BASim.setText("Sim");
        getContentPane().add(BASim);
        BASim.setBounds(180, 470, 50, 23);

        buttonGroup1_Bebidas.add(BANao);
        BANao.setText("Não");
        getContentPane().add(BANao);
        BANao.setBounds(240, 470, 60, 23);

        buttonGroup1_Deficiencia.add(DEsim);
        DEsim.setText("Sim");
        getContentPane().add(DEsim);
        DEsim.setBounds(410, 510, 50, 23);

        buttonGroup1_Deficiencia.add(DEnao);
        DEnao.setText("Não");
        getContentPane().add(DEnao);
        DEnao.setBounds(470, 510, 50, 23);

        buttonGroup1_Doença.add(Dosim);
        Dosim.setText("Sim");
        getContentPane().add(Dosim);
        Dosim.setBounds(630, 470, 50, 23);

        buttonGroup1_Doença.add(DOnao);
        DOnao.setText("Não");
        getContentPane().add(DOnao);
        DOnao.setBounds(690, 470, 60, 23);

        jLabel14.setText("Observações gerais:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 560, 140, 30);

        CampoObservacao.setColumns(20);
        CampoObservacao.setRows(5);
        jScrollPane1.setViewportView(CampoObservacao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 590, 880, 80);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(60, 280, 870, 10);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel15.setText("Registro:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(540, 100, 70, 25);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("cm");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(420, 420, 60, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Altura:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(290, 420, 60, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Peso:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(60, 420, 50, 20);
        getContentPane().add(CampoConsultaN);
        CampoConsultaN.setBounds(590, 310, 70, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Consulta Nº:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(500, 320, 80, 20);
        getContentPane().add(CampoNomeMedico);
        CampoNomeMedico.setBounds(220, 310, 250, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Nome do Médico:");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(60, 320, 110, 20);

        CampoDataAtual.setEnabled(false);
        CampoDataAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDataAtualActionPerformed(evt);
            }
        });
        getContentPane().add(CampoDataAtual);
        CampoDataAtual.setBounds(730, 540, 210, 30);

        jLabel11.setText("Data:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(690, 540, 40, 30);
        getContentPane().add(CampoTratamento);
        CampoTratamento.setBounds(220, 360, 250, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Faz Tratamentos? Quais?:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(60, 370, 150, 20);
        getContentPane().add(CampoRemedio);
        CampoRemedio.setBounds(660, 360, 280, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Toma Remédios? Quais?:");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(500, 370, 150, 20);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(530, 470, 20, 80);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(310, 470, 20, 80);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 153));
        jLabel23.setText("Preencher anamnese:");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(60, 20, 300, 50);

        Fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/left176.png"))); // NOI18N
        Fechar.setToolTipText("");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });
        getContentPane().add(Fechar);
        Fechar.setBounds(900, 690, 40, 39);
        getContentPane().add(CampoAnamneseN);
        CampoAnamneseN.setBounds(780, 310, 70, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Anamnese Nº:");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(690, 320, 80, 20);

        setSize(new java.awt.Dimension(1021, 814));
    }// </editor-fold>//GEN-END:initComponents

    private void CampoBuscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoBuscarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoBuscarNomeActionPerformed

    private void CampoBuscarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoBuscarRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoBuscarRegistroActionPerformed

    private void CampoBuscarRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoBuscarRegistroKeyTyped
        
      
    }//GEN-LAST:event_CampoBuscarRegistroKeyTyped

    private void CampoBuscarNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoBuscarNomeKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_CampoBuscarNomeKeyReleased

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GravarActionPerformed

        try {
            NF_PDF();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Preencher_anamnese.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_GravarActionPerformed

    private void CampoPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesoActionPerformed

    private void CampoDataAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDataAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDataAtualActionPerformed

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        dispose();
    }//GEN-LAST:event_FecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preencher_anamnese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preencher_anamnese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preencher_anamnese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preencher_anamnese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            new Preencher_anamnese().setVisible(true);
               
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BANao;
    private javax.swing.JRadioButton BASim;
    private javax.swing.JTextField CampoAltura;
    private javax.swing.JTextField CampoAnamneseN;
    private javax.swing.JTextField CampoBuscarNome;
    private javax.swing.JTextField CampoBuscarRegistro;
    private javax.swing.JTextField CampoConsultaN;
    private javax.swing.JTextField CampoDataAtual;
    private javax.swing.JTextField CampoDataNasc;
    private javax.swing.JTextField CampoNomeMedico;
    private javax.swing.JTextArea CampoObservacao;
    private javax.swing.JTextField CampoPeso;
    private javax.swing.JTextField CampoRemedio;
    private javax.swing.JTextField CampoTratamento;
    private javax.swing.JRadioButton DEnao;
    private javax.swing.JRadioButton DEsim;
    private javax.swing.JRadioButton DOnao;
    private javax.swing.JRadioButton Dosim;
    private javax.swing.JButton Fechar;
    private javax.swing.JRadioButton Fnao;
    private javax.swing.JRadioButton Fsim;
    private javax.swing.JButton Gravar;
    private javax.swing.JRadioButton UDnao;
    private javax.swing.JRadioButton UDsim;
    private javax.swing.ButtonGroup buttonGroup1_Bebidas;
    private javax.swing.ButtonGroup buttonGroup1_Deficiencia;
    private javax.swing.ButtonGroup buttonGroup1_Doença;
    private javax.swing.ButtonGroup buttonGroup1_Fuma;
    private javax.swing.ButtonGroup buttonGroup2_Drogas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

    
    

 public  void NF_PDF () throws FileNotFoundException  {
        // TODO code application logic here
    
     
    String nomePaciente=CampoBuscarNome.getText().trim(),
    registro=CampoBuscarRegistro.getText().trim(),
    dataNasc=CampoDataNasc.getText().trim();
    
    String nomeMedico=CampoNomeMedico.getText().trim(),
    consultaN=CampoConsultaN.getText().trim(),
    anamneseN=CampoAnamneseN.getText().trim(),
    tratamento=CampoTratamento.getText().trim(),
    remedio=CampoRemedio.getText().trim(),
    peso=CampoPeso.getText().trim(),
    altura=CampoAltura.getText().trim(),
    dataatual=CampoDataAtual.getText().trim();
    
    
    
    
    String bebidas="", drogas="", fumante="", deficiencia="", doencas="";
    String observacao=CampoObservacao.getText().trim();
    
    
    
    //Realiza a captura do radio button 
    if(BASim.isSelected()){
    bebidas="Sim";
    }
    if(BANao.isSelected()) {
            bebidas="Não";}
    
    if(UDsim.isSelected()){
    drogas="Sim";
    }
    if(UDnao.isSelected()) {
            drogas="Não";}
    
     if(Fsim.isSelected()){
    fumante="Sim";
    }
    if(Fnao.isSelected()) {
            fumante="Não";}
    
     if(DEsim.isSelected()){
    deficiencia="Sim";
    }
    if(DEnao.isSelected()) {
            deficiencia="Não";}
    
     if(Dosim.isSelected()){
    doencas="Sim";
    }
    if(DOnao.isSelected()) {
            doencas="Não";}
    
    
    
    
    
    
    
    
    
    
    
    Document documentoPDF = new Document();
     
    try{
        
        //Cria uma instancia do doc e nomeia o PDF.
        PdfWriter instance = PdfWriter.getInstance(documentoPDF,new FileOutputStream(anamneseN+"_anamnese.pdf"));
        
    
        //abrir o documento
        documentoPDF.open();
        
        //setar tamanho da pagina
        documentoPDF.setPageSize(PageSize.A4);
        
        //Adicionando primeiro paragrafo.
        
        
        
         
        documentoPDF.add(new Paragraph("\nAnamnese Nº:\t"+anamneseN
                + "\nData da anamnese:\t"+dataatual ));
        
        documentoPDF.add(new Paragraph("_____________________________________________________________________________"));

        
        documentoPDF.add(new Paragraph("\nHospital Anhembi Morumbi"
          + "\nEndereço: R.Casa do Ator, 1233 - Vila Olimpia \t  Tel: 011-1233 1232\n"
          + "Municipio: São Paulo \t UF: SP"  ));
        
        documentoPDF.add(new Paragraph("_____________________________________________________________________________"));
      
        documentoPDF.add(new Paragraph("\nNome do Paciente: "+nomePaciente+"\t \t \t Registro: "+registro+"\n Data de nascimento: "+dataNasc));
        
        documentoPDF.add(new Paragraph("\n_____________________________________________________________________________"));
        
      
        
        
        
        
         documentoPDF.add(new Paragraph("\nMédico:\t"+nomeMedico
                 + "\nConsulta Nº:\t"+consultaN
                 + "\nTratamentos:\t"+tratamento
                 + "\nRemedios:\t"+remedio
                 + "\nPeso:\t"+peso
                 + "\nAltura:\t"+altura
                 
               
         ));
         
         
         
         
         
         
         documentoPDF.add(new Paragraph("\nIngeri bebidas alcoolicas:\t"+bebidas
          + "\nUsa drogas:\t"+drogas
          + "\nFuma:\t"+fumante
          + "\nDeficiencia fisica:\t"+deficiencia
          + "\nDoenças:\t"+doencas
         ));
         
         
       
         
         
         documentoPDF.add(new Paragraph("_____________________________________________________________________________"));
         
         documentoPDF.add(new Paragraph("\nDescrição: "+observacao));
         
         documentoPDF.add(new Paragraph("_____________________________________________________________________________"));
         
        //Busca e abre o arquivo PDF.
         java.awt.Desktop.getDesktop().open( new File(anamneseN+"_anamnese.pdf" ) ); 
        
    }
            
            catch(DocumentException de){
                    de.printStackTrace();
                    }
                                        
            catch(IOException ioe){
                ioe.printStackTrace();
                
                
            }     
            finally{
        documentoPDF.close();
    }        


 }
    

}